version: '3'
services:
  client:
    build: client
    volumes:
      - ./client:/app:rw
    ports:
      - "8080:8080"
    environment:
      API_URL: "http://localhost"
      API_PORT: 80
  server:
    build: server
    command: nginx -g "daemon off;"
    links:
      - api
    ports:
      - "80:80"
  api:
    build: api
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db
      - cache
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: todolist
      DB_USERNAME: arnel
      DB_PASSWORD: secret
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todolist
      MYSQL_USER: arnel
      MYSQL_PASSWORD: secret
  cache:
    image: memcached
